[package]
name = "dbx"
version = "0.1.0"
edition = "2021"

[features]
tokio-postgres = [ "dep:tokio-postgres", "indexed-args" ]
mysql-async = [ "dep:mysql_async", "dep:mysql_common" ]
indexed-args = []

default = ["mysql-async"]

[dependencies]
futures-util = { version = "0.3", default-features = false }
thiserror = "1.0"
mysql_async = { version = "0.34", features = ["minimal"], default-features = false, optional = true }
mysql_common = { version = "0.32", optional = true }
tokio-postgres = { version = "0.7", default-features = false, optional = true }