[workspace]
members = [
	"crates/core",
	"crates/macros",
	"crates/migrate",
	"examples/drivers",
	"examples/pools",
	"tests/e2e-mysql",
	"tests/e2e-postgres",
]

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.2.2"

[features]
derive = [ "dep:esql-macros", "esql-macros/derive" ]
migrate = [ "dep:esql-macros", "dep:esql-migrate", "esql-core/migrate", "esql-macros/migrate" ]
mysql = [ "esql-core/mysql" ]
postgres = [ "esql-core/postgres" ]
with-time-0_3 = [ "esql-core/with-time-0_3" ]
with-uuid-1 = [ "esql-core/with-uuid-1" ]

[package]
name = "esql"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
esql-core = { path = "crates/core" }
esql-macros = { path = "crates/macros", optional = true }
esql-migrate = { path = "crates/migrate", optional = true }
