[package]
name = "example-drivers"
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[dependencies]
esql = { workspace = true, features = ["derive", "migrate", "mysql", "postgres"] }
mysql_async = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
