[package]
name = "example-drivers"
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[features]
default = ["mysql"]
mysql = ["esql/mysql", "dep:mysql_async"]
postgres = ["esql/postgres", "dep:tokio-postgres"]

[dependencies]
esql = { workspace = true, features = ["derive", "migrate"] }
mysql_async = { workspace = true, optional = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true, optional = true }
