[package]
name = "esql-macros"
description = "Derive and migration macros for the `esql` crate"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
proc-macro = true

[features]
derive = []
migrate = [ "dep:esql-migrate" ]

[dependencies]
esql-migrate = { workspace = true, optional = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
