[package]
name = "esql-macros"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
proc-macro = true

[features]
derive = []
migrate = [ "dep:esql-migrate" ]

[dependencies]
esql-migrate = { workspace = true, optional = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
