[package]
name = "example-pools"
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[dependencies]
esql = { workspace = true, features = ["postgres"] }
bb8 = { workspace = true }
bb8-postgres = { workspace = true }
deadpool-postgres = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
