[package]
name = "esql-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
migrate = []
mysql = [ "dep:mysql_async" ]
postgres = [ "dep:tokio-postgres" ]
with-time-0_3 = [ "dep:time", "tokio-postgres?/with-time-0_3" ]
with-uuid-1 = [ "dep:uuid", "tokio-postgres?/with-uuid-1" ]

[dependencies]
futures-util = { workspace = true }
mysql_async = { workspace = true, optional = true }
time = { workspace = true, optional = true }
tokio-postgres = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }
